[package]
name = "axum-valid"
version = "0.5.1"
description = "Validation tools for axum using the validator library."
authors = ["GengTeng <me@gteng.org>"]
license = "MIT"
homepage = "https://github.com/gengteng/axum-valid"
repository = "https://github.com/gengteng/axum-valid"
keywords = [
    "http",
    "web",
    "framework",
    "validator",
]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming",
]
edition = "2021"

[dependencies]
axum = { version = "0.6.18", default-features = false }
validator = "0.16.0"

[dependencies.axum-msgpack]
version = "0.3.0"
default-features = false
optional = true

[dependencies.axum-yaml]
version = "0.3.0"
default-features = false
optional = true

[dependencies.axum-extra]
version = "0.7.6"
default-features = false
optional = true

[dev-dependencies]
anyhow = "1.0.72"
axum = { version = "0.6.19" }
tokio = { version = "1.29.1", features = ["full"] }
hyper = { version = "0.14.27", features = ["full"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.181", features = ["derive"] }
validator = { version = "0.16.0", features = ["derive"] }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
mime = "0.3.17"
prost = "0.11.9"
once_cell = "1.18.0"
rmp-serde = "1.1.2"

[features]
default = ["json", "form", "query"]
json = ["axum/json"]
form = ["axum/form"]
query = ["axum/query"]
typed_header = ["axum/headers"]
msgpack = ["axum-msgpack"]
yaml = ["axum-yaml"]
into_json = ["json"]
422 = []
extra = ["axum-extra"]
extra_query = ["axum-extra/query"]
extra_form = ["axum-extra/form"]
extra_protobuf = ["axum-extra/protobuf"]
all_extra_types = ["extra", "extra_query", "extra_form", "extra_protobuf"]
all_types = ["json", "form", "query", "typed_header", "msgpack", "yaml", "all_extra_types"]
full = ["all_types", "422", "into_json"]
