[package]
name = "axum-valid"
version = "0.2.2"
description = "Validation tools for axum using the validator library."
authors = ["GengTeng <me@gteng.org>"]
license = "MIT"
homepage = "https://github.com/gengteng/axum-valid"
repository = "https://github.com/gengteng/axum-valid"
keywords = [
    "http",
    "web",
    "framework",
    "validator",
]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming",
]
edition = "2021"

[dependencies]
axum = "0.6.18"
validator = "0.16.0"
